import { classAmulets } from "objects/classAmulets";
import { classArmors } from "objects/classArmors";
import { classAxes } from "objects/classAxes";
import { classBows } from "objects/classBows";
import { classElixirs } from "objects/classElixirs";
import { classHelmets } from "objects/classHelmets";
import { classMaces } from "objects/classMaces";
import { classOils } from "objects/classOils";
import { classPotions } from "objects/classPotions";
import { classRings } from "objects/classRings";
import { classRunes } from "objects/classRunes";
import { classShields } from "objects/classShields";
import { classStaffs } from "objects/classStaffs";
import { classSwords } from "objects/classSwords";

export class Object {
  constructor(ObjectID){
    const allObjectData = {
      1  : { type: "potion", linkID : 1 },
      2  : { type: "potion", linkID : 2 },
      3  : { type: "potion", linkID : 3 },
      4  : { type: "potion", linkID : 4 },
      5  : { type: "potion", linkID : 5 },
      6  : { type: "potion", linkID : 6 },
       
      7  : { type: "elixir", linkID : 1, },
      8  : { type: "elixir", linkID : 2, },
      9  : { type: "elixir", linkID : 3, },
      10 : { type: "elixir", linkID : 4, },
      11 : { type: "elixir", linkID : 5, },
      
      12 : { type: "rune", linkID : 1, },
      13 : { type: "rune", linkID : 2, },
      14 : { type: "rune", linkID : 3, },
      15 : { type: "rune", linkID : 4, },
      16 : { type: "rune", linkID : 5, },
    
      17 : { type: "oils", linkID : 1, },
      18 : { type: "oils", linkID : 2, },
      19 : { type: "oils", linkID : 3, },
      20 : { type: "oils", linkID : 4, },
      21 : { type: "oils", linkID : 5, },
      22 : { type: "oils", linkID : 6, },
      23 : { type: "oils", linkID : 7, },
      24 : { type: "oils", linkID : 8, },
      25 : { type: "oils", linkID : 9, },
      26 : { type: "oils", linkID : 10,},
    
      27 : { type: "rings", linkID : 1,  },
      28 : { type: "rings", linkID : 2,  },
      29 : { type: "rings", linkID : 3,  },
      30 : { type: "rings", linkID : 4,  },
      31 : { type: "rings", linkID : 5,  },
      32 : { type: "rings", linkID : 6,  },
      33 : { type: "rings", linkID : 7,  },
      34 : { type: "rings", linkID : 8,  },
      35 : { type: "rings", linkID : 9,  },
      36 : { type: "rings", linkID : 10, },
      37 : { type: "rings", linkID : 11, },
      38 : { type: "rings", linkID : 12, },
      39 : { type: "rings", linkID : 13, },
      40 : { type: "rings", linkID : 14, },
      41 : { type: "rings", linkID : 15, },
    
      42 : { type: "amulets", linkID : 1, },
      43 : { type: "amulets", linkID : 2, },
      44 : { type: "amulets", linkID : 3, },
      45 : { type: "amulets", linkID : 4, },
    
      46 : { type: "bows", linkID : 1,  },
      47 : { type: "bows", linkID : 2,  },
      48 : { type: "bows", linkID : 3,  },
      49 : { type: "bows", linkID : 4,  },
      50 : { type: "bows", linkID : 5,  },
      51 : { type: "bows", linkID : 6,  },
      52 : { type: "bows", linkID : 7,  },
      53 : { type: "bows", linkID : 8,  },
      54 : { type: "bows", linkID : 9,  },
      55 : { type: "bows", linkID : 10, },
      56 : { type: "bows", linkID : 11, },
      57 : { type: "bows", linkID : 12, },
      58 : { type: "bows", linkID : 13, },
      59 : { type: "bows", linkID : 14, },
      60 : { type: "bows", linkID : 15, },
      61 : { type: "bows", linkID : 16, },
      62 : { type: "bows", linkID : 17, },
      63 : { type: "bows", linkID : 18, },
    
      64 : { type: "staff", linkID : 1,  },
      65 : { type: "staff", linkID : 2,  },
      66 : { type: "staff", linkID : 3,  },
      67 : { type: "staff", linkID : 4,  },
      68 : { type: "staff", linkID : 5,  },
      69 : { type: "staff", linkID : 6,  },
      70 : { type: "staff", linkID : 7,  },
      71 : { type: "staff", linkID : 8,  },
      72 : { type: "staff", linkID : 9,  },
      73 : { type: "staff", linkID : 10, },
      74 : { type: "staff", linkID : 11, },
      75 : { type: "staff", linkID : 12, },
      76 : { type: "staff", linkID : 13, },
      77 : { type: "staff", linkID : 14, },
    
      78 : { type: "mace", linkID : 1,  },
      79 : { type: "mace", linkID : 2,  },
      80 : { type: "mace", linkID : 3,  },
      81 : { type: "mace", linkID : 4,  },
      82 : { type: "mace", linkID : 5,  },
      83 : { type: "mace", linkID : 6,  },
      84 : { type: "mace", linkID : 7,  },
      85 : { type: "mace", linkID : 8,  },
      86 : { type: "mace", linkID : 9,  },
      87 : { type: "mace", linkID : 10, },
      88 : { type: "mace", linkID : 11, },
      89 : { type: "mace", linkID : 12, },
      90 : { type: "mace", linkID : 13, },
      91 : { type: "mace", linkID : 14, },
      92 : { type: "mace", linkID : 15, },
      93 : { type: "mace", linkID : 16, },
      94 : { type: "mace", linkID : 17, },
    
      95  : { type: "axe", linkID : 1,  },
      96  : { type: "axe", linkID : 2,  },
      97  : { type: "axe", linkID : 3,  },
      98  : { type: "axe", linkID : 4,  },
      99  : { type: "axe", linkID : 5,  },
      100 : { type: "axe", linkID : 6,  },
      101 : { type: "axe", linkID : 7,  },
      102 : { type: "axe", linkID : 8,  },
      103 : { type: "axe", linkID : 9,  },
      104 : { type: "axe", linkID : 10, },
      105 : { type: "axe", linkID : 11, },
      106 : { type: "axe", linkID : 12, },
      107 : { type: "axe", linkID : 13, },
      108 : { type: "axe", linkID : 14, },
      109 : { type: "axe", linkID : 15, },
      110 : { type: "axe", linkID : 16, },
    
      111 : { type: "sword", linkID : 1,  },
      112 : { type: "sword", linkID : 2,  },
      113 : { type: "sword", linkID : 3,  },
      114 : { type: "sword", linkID : 4,  },
      115 : { type: "sword", linkID : 5,  },
      116 : { type: "sword", linkID : 6,  },
      117 : { type: "sword", linkID : 7,  },
      118 : { type: "sword", linkID : 8,  },
      119 : { type: "sword", linkID : 9,  },
      120 : { type: "sword", linkID : 10, },
      121 : { type: "sword", linkID : 11, },
      122 : { type: "sword", linkID : 12, },
      123 : { type: "sword", linkID : 13, },
      124 : { type: "sword", linkID : 14, },
      125 : { type: "sword", linkID : 15, },
      126 : { type: "sword", linkID : 16, },
      127 : { type: "sword", linkID : 17, },
      128 : { type: "sword", linkID : 18, },
      129 : { type: "sword", linkID : 19, },
      130 : { type: "sword", linkID : 20, },
      131 : { type: "sword", linkID : 21, },
      132 : { type: "sword", linkID : 22, },
      133 : { type: "sword", linkID : 23, },
      134 : { type: "sword", linkID : 24, },
      135 : { type: "sword", linkID : 25, },
      136 : { type: "sword", linkID : 26, },
      137 : { type: "sword", linkID : 27, },
      138 : { type: "sword", linkID : 28, },
      139 : { type: "sword", linkID : 29, },
      140 : { type: "sword", linkID : 30, },
      141 : { type: "sword", linkID : 31, },
      142 : { type: "sword", linkID : 32, },
      143 : { type: "sword", linkID : 33, },
    
      144 : { type: "shield", linkID : 1,  },
      145 : { type: "shield", linkID : 2,  },
      146 : { type: "shield", linkID : 3,  },
      147 : { type: "shield", linkID : 4,  },
      148 : { type: "shield", linkID : 5,  },
      149 : { type: "shield", linkID : 6,  },
      150 : { type: "shield", linkID : 7,  },
      151 : { type: "shield", linkID : 8,  },
      152 : { type: "shield", linkID : 9,  },
      153 : { type: "shield", linkID : 10, },
      154 : { type: "shield", linkID : 11, },
      155 : { type: "shield", linkID : 12, },
    
      156 : { type: "armor", linkID : 1,  },
      157 : { type: "armor", linkID : 2,  },
      158 : { type: "armor", linkID : 3,  },
      159 : { type: "armor", linkID : 4,  },
      160 : { type: "armor", linkID : 5,  },
      161 : { type: "armor", linkID : 6,  },
      162 : { type: "armor", linkID : 7,  },
      163 : { type: "armor", linkID : 8,  },
      164 : { type: "armor", linkID : 9,  },
      165 : { type: "armor", linkID : 10, },
      166 : { type: "armor", linkID : 11, },
      167 : { type: "armor", linkID : 12, },
      168 : { type: "armor", linkID : 13, },
      169 : { type: "armor", linkID : 14, },
      170 : { type: "armor", linkID : 15, },
      171 : { type: "armor", linkID : 16, },
      172 : { type: "armor", linkID : 17, },
      173 : { type: "armor", linkID : 18, },
      174 : { type: "armor", linkID : 19, },
      175 : { type: "armor", linkID : 20, },
      176 : { type: "armor", linkID : 21, },
      177 : { type: "armor", linkID : 22, },
      178 : { type: "armor", linkID : 23, },
      179 : { type: "armor", linkID : 24, },
      180 : { type: "armor", linkID : 25, },
      181 : { type: "armor", linkID : 26, },
      182 : { type: "armor", linkID : 27, },
      183 : { type: "armor", linkID : 28, },
      184 : { type: "armor", linkID : 29, },
      185 : { type: "armor", linkID : 30, },
      186 : { type: "armor", linkID : 31, },
      187 : { type: "armor", linkID : 32, },
    
      188 : { type: "helmet", linkID : 1,  },
      189 : { type: "helmet", linkID : 2,  },
      190 : { type: "helmet", linkID : 3,  },
      191 : { type: "helmet", linkID : 4,  },
      192 : { type: "helmet", linkID : 5,  },
      193 : { type: "helmet", linkID : 6,  },
      194 : { type: "helmet", linkID : 7,  },
      195 : { type: "helmet", linkID : 8,  },
      196 : { type: "helmet", linkID : 9,  },
      197 : { type: "helmet", linkID : 10, },
      198 : { type: "helmet", linkID : 11, },
      199 : { type: "helmet", linkID : 12, },
      200 : { type: "helmet", linkID : 13, },
      201 : { type: "helmet", linkID : 14, },
      202 : { type: "helmet", linkID : 15, },
      203 : { type: "helmet", linkID : 16, },
     };
    const objectData = allObjectData[ObjectID];
    const classMap = {
      amulets: classAmulets,
      armor: classArmors,
      axe: classAxes,
      bows: classBows,
      elixir: classElixirs,
      helmet: classHelmets,
      mace: classMaces,
      oils: classOils,
      potion: classPotions,
      rings: classRings,
      rune: classRunes,
      shield: classShields,
      staff: classStaffs,
      sword: classSwords,
    };
    const ClassConstructor = classMap[objectData.type];
    if (ClassConstructor) {
      return new ClassConstructor(ObjectID, objectData.linkID);
    }
  }
}
